src/objects/AnyLabel__c.object
<CustomObject>
    <fields>
        <fullName>Assignee__c</fullName>
        <label>Assignee</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SObject</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Background_Color__c</fullName>
        <label>Background Color</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Font_Color__c</fullName>
        <label>Font Color</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>AnyLabel</label>
    <nameField>
        <label>Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AnyLabels</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/SObject.globalValueSet
<!--
  ~ Copyright (c) 2020.  adelForce (Adelchi Ltd)
  ~  All Rights Reserved
  ~  NOTICE:  All information contained herein is, and remains the property of adelForce (Adelchi Ltd) .
  ~  The intellectual and technical concepts contained are protected by trade secret or copyright law.
  ~  Dissemination of this information or reproduction of this material is strictly forbidden unless prior written permission is obtained from  adelForce (Adelchi Ltd).
  -->

<GlobalValueSet>
    <customValue>
        <fullName>Contract</fullName>
    </customValue>
    <customValue>
        <fullName>Order</fullName>
    </customValue>
    <customValue>
        <fullName>Campaign</fullName>
    </customValue>
    <customValue>
        <fullName>CampaignMember</fullName>
    </customValue>
    <customValue>
        <fullName>Account</fullName>
    </customValue>
    <customValue>
        <fullName>Contact</fullName>
    </customValue>
    <customValue>
        <fullName>Lead</fullName>
    </customValue>
    <customValue>
        <fullName>Opportunity</fullName>
    </customValue>
    <customValue>
        <fullName>Asset</fullName>
    </customValue>
    <customValue>
        <fullName>Case</fullName>
    </customValue>
    <customValue>
        <fullName>Solution</fullName>
    </customValue>
    <customValue>
        <fullName>Idea</fullName>
    </customValue>
    <customValue>
        <fullName>AnyLabel_Setup_Trigger__c</fullName>
    </customValue>
    <customValue>
        <fullName>AnyLabelTrigger__c</fullName>
    </customValue>
    <masterLabel>SObject</masterLabel>
</GlobalValueSet>

src/classes/AnyLabelCtrlTest.cls
/**
 * Created by Adelchi on 18/04/2020.
 * Purpose : (Write a succinct description of this class here.)
 */


@IsTest
private class AnyLabelCtrlTest {
    public static AnyLabel__c anyL = new AnyLabel__c(
            Assignee__c = 'Account',
            Background_Color__c = '#122222',
            Font_Color__c = 'white',
            Name = 'LabelTest'
    );
    public static Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
    public static User u = new User(
            Alias = 'admin',
            Email='adminuser@testorg.com',
            EmailEncodingKey='UTF-8',
            LastName='Testing',
            LanguageLocaleKey='en_US',
            LocaleSidKey='en_US',
            ProfileId = p.Id,
            TimeZoneSidKey='America/Los_Angeles',
            UserName='adminuser@testorg.com'
    );
    public static User us = new User(
            Alias = 'admins',
            Email='adminusers@testorg.com',
            EmailEncodingKey='UTF-8',
            LastName='Testings',
            LanguageLocaleKey='en_US',
            LocaleSidKey='en_US',
            ProfileId = p.Id,
            TimeZoneSidKey='America/Los_Angeles',
            UserName='adminusers@testorg.com'
    );
    public static AnyLabel__Share shareInsert = new AnyLabel__Share(
            AccessLevel = 'All',
            UserOrGroupId = u.Id,
            ParentId = anyL.Id
    );
    public static Account acc = new Account(
            Name = 'testaccount'
    );
    @IsTest
    static void testBehavior () {
        insert u;
        insert us;
        insert anyL;
        Database.insert(shareInsert,false);
        System.runAs(u){
            System.assert(AnyLabelCtrl.isAdmin());
        }
        System.runAs(us){
            System.assert(AnyLabelCtrl.isAdmin());
        }
        System.assert(AnyLabelCtrl.getGlobalLabels().size()>0);
        insert acc;
        AnyLabelCtrl.NewLabel(acc.Id, '#122222', 'white', 'LabelTest');
        acc.Labels__c = 'LabelTest;';
        update acc;
        System.assert(AnyLabelCtrl.getSObjectLabelsListAll(acc.Id).size()>0);
        System.assert(AnyLabelCtrl.getAssignedLabelsList(acc.Id).size()>0);
    }
}